### ISSUE TITLE
OS X zip file in readme is an ELF executable

### ISSUE THREAD

**Issue by wizardfrag** [lukasmartinelli/redis-pipe#1]
```shell
~ » unzip redis-pipe-v1.4.1-darwin-amd64.zip
Archive:  redis-pipe-v1.4.1-darwin-amd64.zip
  inflating: redis-pipe
~ » ./redis-pipe
zsh: exec format error: ./redis-pipe
~ » which
~ » file redis-pipe
redis-pipe: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), not stripped
```

Should look something like:
```shell
~ » file `which bash`
/bin/bash: Mach-O 64-bit executable x86_64
```

**Comment by lukasmartinelli** [comment]
Oh no I am very sorry. It is my first time I crosscompiled a Go project.
I will try to fix that asap.

**Comment by wizardfrag** [comment]
It's fine. I can provide a compiled file if you wish. I just thought I'd let you know so it can be fixed.

Are you using goxc?

**Comment by lukasmartinelli** [comment]
No I tried using `goxc` but somehow did not get it to work. I used the official Golang docker image to crosscompile but I simply used `go build` with `GOOS` and `GOARCH`.

But perhaps I should use ` go build --ldflags '-extldflags "-static"'`

Wow would be very nice if you could provide that.

**Comment by lukasmartinelli** [comment]
So I compiled it now with `GOOS=darwin GOARCH=amd64 go build --ldflags '-extldflags "-static"'`.
Does it work now?

**Comment by wizardfrag** [comment]
That works now, well done!

I was just going to fork it to use goxc...

**Comment by lukasmartinelli** [comment]
Ah no something was still fishy on the darwin side. I used `goxc` now and republished the releases.
Thanks man for the fast reaction! Really appreciate it.

**Comment by wizardfrag** [comment]
No, thank you for the quick response!
